### PR TITLE
Initialization of independent Customer Intelligence Read Model codebase

### PR DESCRIPTION
**Pull request by denisivan0v**
This change is [Reviewable](https://reviewable.io/reviews/2gis/nuclear-river-customer-intelligence/1)

### CODE REVIEW

**Comment by denisivan0v** [comment]
@rechkalov @maximpashuk take a look

**Comment by maximpashuk** [comment]
:lgtm:

---

Reviewed 465 of 465 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river-customer-intelligence/1#-:-KPGjBAAMtHfcoFYzLr8:bnfp4nl)_

**Comment by maximpashuk** [comment]
папка CustomerIntelligence.Replication.DataTest.Model должна быть CustomerIntelligence.Replication.StateInitialization.Tests

также в solution не .nuget папки с файлом nuget.config, он из-за не участвует в поиске по solution

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river-customer-intelligence/1#-:-KPHXPoyitX3Vv2F4Mfw:b-ymg1h7)_

**Comment by denisivan0v** [comment]
Done

---

Review status: 429 of 470 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river-customer-intelligence/1#-:-KPHjGC2ZOFibjzzYHCT:bb6un1j)_

**Comment by maximpashuk** [comment]
:lgtm:

---

Reviewed 70 of 70 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/2gis/nuclear-river-customer-intelligence/1#-:-KPHkOaYBxpPIkLEFrff:bnfp4nl)_

**Pull request merged**
